language: generic
sudo: required
services:
  - docker

#before_install:
  #- docker build -t ahmedaminesoltani/react-test -f ./client/Dockerfile.dev ./client

#script:
  #- docker container run  -e CI=true  ahmedaminesoltani/react-test npm run test
##  - bash docker_push.sh

#after_success:
  #- docker build -t ahmedaminesoltani/multi-client  ./client
  #- docker build -t ahmedaminesoltani/multi-worker  ./worker
  #- docker build -t ahmedaminesoltani/multi-nginx   ./nginx
  #- docker build -t ahmedaminesoltani/multi-server  ./server
  #- echo "$DOCKER_PASSWORD"  |  docker login -u "$DOCKER_ID" --password-stdin
##  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  #- docker push ahmedaminesoltani/multi-client
  #- docker push ahmedaminesoltani/multi-worker
  #- docker push ahmedaminesoltani/multi-nginx 
  #- docker push ahmedaminesoltani/multi-server
deploy:
  edge: true
  provider: elasticbeanstalk 
  region: "eu-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-771253377026"
  bucket_path: "multi-docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY