version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=azerty123
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    image: 'ahmedaminesoltani/multi-server:latest'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=azerty123
      - PGPORT=5432
  client:
    image: 'ahmedaminesoltani/multi-client:latest'
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    image: 'ahmedaminesoltani/multi-worker:latest'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app